Repository 2024Workey/workey-client, pull requests merged in 2024-06, with the labels that each got.

#95 :bug: [refactor] 한 자릿수의 날일 경우 앞의 0을 제거하여 출력
  js/list.js
Labels: 🔨 Refactor

#96 :recycle: [refactor] 한 자릿수의 날일 경우 Number로 앞의 0을 제거하여 출력
  js/list.js
Labels: 🔨 Refactor

#98 🐛 [refactor] 날짜로부터 quesId 도출 성공
  js/diary-reading.js
  js/diary.js
  js/list.js
Labels: 🔨 Refactor

#99 :bug: [refactor] mypage에서 사용자가 작성하나 diary 개수 get 완성
  js/mypage.js
Labels: 🔨 Refactor

#100 [fix] payday 계산 문제 해결
  js/index.js
Labels: 🔨 Refactor

#101 :recycle: [refactor] diary를 보기만 할 때는 값 수정 락 걸기
  join.html
  js/diary.js
  js/mypage.js
Labels: ✨ Feature

#102 🐛 [refactor] payday값을 string으로 전달
  js/mypage.js
Labels: 🔨 Refactor

#103 :recycle: [refactor] diary를 볼 때 락 거는 함수 생성 및 적용
  js/diary-reading.js
  js/diary.js
Labels: 🔨 Refactor

#105 :sparkles: [feat] diary 수정 구현
  css/diary.css
  diary.html
  js/diary.js
  js/list.js
Labels: ✨ Feature

#107 :bug: [refactor] diary post api 500 error 해결
  css/diary.css
  diary.html
  js/diary.js
Labels: 🔨 Refactor

#112 :bug: [refactor] diary 검색 공백, 대소문자 상관없이 검색 구현
  js/list.js
Labels: 🔨 Refactor

#116 :recycle: [refactor] 회사 GET API 연동 성공
  join.html
  js/join.js
Labels: 🐞 Bug

#118 :bug: [refactor] 회원가입 페이지의 회사 Others 저장 및 드롭다운 구현
  join.html
  js/join.js
Labels: 🔨 Refactor

#120 :bug: [refactor] Others 회사 저장됨
  js/join.js
Labels: 🔨 Refactor

#121 :sparkles: [feat] 각 diary마다 쓰여질, 또는 쓰여진 날짜 포맷팅
  diary.html
  js/diary.js
  js/list.js
Labels: ✨ Feature

#122 💄 [design] 날짜 버튼 삭제
  css/list.css
  list.html
Labels: 🔨 Refactor

#124 :bug: [refactor] mypage의 회사 변경 오류 해결
  diary.html
  join.html
  js/join.js
  js/mypage.js
  list.html
Labels: 🔨 Refactor

#127 :lipstick: [design] nav bar 둥글게 보이던 ui 수정
  css/style.css
Labels: 🔨 Refactor

#131 :sparkles: [feat] RDS, EC2 배포한 서버 URL 적용
  .gitignore
  js/diary.js
  js/index.js
  js/join.js
  js/list.js
  js/login.js
  js/mypage.js
  js/ranking.js
  node_modules/.package-lock.json
  node_modules/dotenv/CHANGELOG.md
  node_modules/dotenv/LICENSE
  node_modules/dotenv/README-es.md
  node_modules/dotenv/README.md
  node_modules/dotenv/config.d.ts
  node_modules/dotenv/config.js
  node_modules/dotenv/lib/cli-options.js
  node_modules/dotenv/lib/env-options.js
  node_modules/dotenv/lib/main.d.ts
  node_modules/dotenv/lib/main.js
  node_modules/dotenv/package.json
  package-lock.json
  package.json
Labels: 🌏 Deploy

#132 :recycle: [bug] user name, question get 성공
  js/diary.js
  js/list.js
Labels: 🐞 Bug

#133 :sparkles: [feat] mypage, diary put 적용
  js/diary.js
  js/mypage.js
Labels: ✨ Feature
